--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/9/2018 21:54:13
-- Server version: 5.5.5-10.1.34-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE tiendacomics;

--
-- Drop table `dibujantecomic`
--
DROP TABLE IF EXISTS dibujantecomic;

--
-- Drop table `guionistacomic2`
--
DROP TABLE IF EXISTS guionistacomic2;

--
-- Drop table `comicpersonajes`
--
DROP TABLE IF EXISTS comicpersonajes;

--
-- Drop table `detallecompra`
--
DROP TABLE IF EXISTS detallecompra;

--
-- Drop table `detalleventa`
--
DROP TABLE IF EXISTS detalleventa;

--
-- Drop table `digujantecomic`
--
DROP TABLE IF EXISTS digujantecomic;

--
-- Drop table `guionistacomic`
--
DROP TABLE IF EXISTS guionistacomic;

--
-- Drop table `tipoespecial`
--
DROP TABLE IF EXISTS tipoespecial;

--
-- Drop table `comic`
--
DROP TABLE IF EXISTS comic;

--
-- Drop table `personajes`
--
DROP TABLE IF EXISTS personajes;

--
-- Drop table `factura`
--
DROP TABLE IF EXISTS factura;

--
-- Drop table `venta`
--
DROP TABLE IF EXISTS venta;

--
-- Drop table `dibujante`
--
DROP TABLE IF EXISTS dibujante;

--
-- Drop table `guionista`
--
DROP TABLE IF EXISTS guionista;

--
-- Drop table `facturac`
--
DROP TABLE IF EXISTS facturac;

--
-- Drop table `compra`
--
DROP TABLE IF EXISTS compra;

--
-- Drop table `distribuidora`
--
DROP TABLE IF EXISTS distribuidora;

--
-- Set default database
--
USE tiendacomics;

--
-- Create table `distribuidora`
--
CREATE TABLE distribuidora (
  codigodistribuidora int(11) NOT NULL,
  nombredistribuidora varchar(55) DEFAULT NULL,
  telefono int(11) DEFAULT NULL,
  pais varchar(55) DEFAULT NULL,
  PRIMARY KEY (codigodistribuidora)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `compra`
--
CREATE TABLE compra (
  numerocompra int(11) NOT NULL,
  fecha date DEFAULT NULL,
  codigodistribuidor int(11) DEFAULT NULL,
  PRIMARY KEY (numerocompra)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE compra
ADD CONSTRAINT FK_compra_distribuidora_codigodistribuidora FOREIGN KEY (codigodistribuidor)
REFERENCES distribuidora (codigodistribuidora) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `facturac`
--
CREATE TABLE facturac (
  numerocompra int(11) NOT NULL,
  nit int(11) DEFAULT NULL,
  nombre varchar(55) DEFAULT NULL,
  PRIMARY KEY (numerocompra)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE facturac
ADD CONSTRAINT FK_facturac_compra_numerocompra FOREIGN KEY (numerocompra)
REFERENCES compra (numerocompra) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `guionista`
--
CREATE TABLE guionista (
  codigoGuionista int(11) NOT NULL,
  nombreGuionista varchar(255) DEFAULT NULL,
  PRIMARY KEY (codigoGuionista)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `dibujante`
--
CREATE TABLE dibujante (
  codigodibujante int(11) NOT NULL AUTO_INCREMENT,
  nombredibujante varchar(255) DEFAULT NULL,
  PRIMARY KEY (codigodibujante)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `venta`
--
CREATE TABLE venta (
  numeroVenta int(11) NOT NULL,
  fecha date DEFAULT NULL,
  PRIMARY KEY (numeroVenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `factura`
--
CREATE TABLE factura (
  numeroVenta int(11) NOT NULL,
  NIT int(11) DEFAULT NULL,
  nombre varchar(55) DEFAULT NULL,
  PRIMARY KEY (numeroVenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE factura
ADD CONSTRAINT FK_factura_venta_numeroVenta FOREIGN KEY (numeroVenta)
REFERENCES venta (numeroVenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `personajes`
--
CREATE TABLE personajes (
  codigoPersonaje int(11) NOT NULL AUTO_INCREMENT,
  nombrePersonaje varchar(255) DEFAULT NULL,
  PRIMARY KEY (codigoPersonaje)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `comic`
--
CREATE TABLE comic (
  codigoComic bigint(20) NOT NULL,
  Titulo varchar(100) DEFAULT NULL,
  numeroComic int(11) DEFAULT NULL,
  añoPublicacion year(4) DEFAULT NULL,
  editorial varchar(255) DEFAULT NULL,
  descripcion varchar(255) DEFAULT NULL,
  precio double DEFAULT NULL,
  PRIMARY KEY (codigoComic)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 8192,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `tipoespecial`
--
CREATE TABLE tipoespecial (
  codigoComic bigint(20) NOT NULL,
  tipoEspecial varchar(55) NOT NULL,
  PRIMARY KEY (codigoComic, tipoEspecial)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE tipoespecial
ADD CONSTRAINT FK_tipoespecial_comic_codigoComic FOREIGN KEY (codigoComic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `guionistacomic`
--
CREATE TABLE guionistacomic (
  codigoGuionista int(11) NOT NULL,
  codigoComic bigint(20) NOT NULL,
  PRIMARY KEY (codigoGuionista, codigoComic)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE guionistacomic
ADD CONSTRAINT FK_guionistacomic_comic_codigoComic FOREIGN KEY (codigoComic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE guionistacomic
ADD CONSTRAINT FK_guionistacomic_guionista_codigoGuionista FOREIGN KEY (codigoGuionista)
REFERENCES guionista (codigoGuionista) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `digujantecomic`
--
CREATE TABLE digujantecomic (
  codigoComic bigint(20) NOT NULL,
  codigoDibujante int(11) NOT NULL,
  PRIMARY KEY (codigoComic, codigoDibujante)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE digujantecomic
ADD CONSTRAINT FK_digujantecomic_comic_codigoComic FOREIGN KEY (codigoComic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE digujantecomic
ADD CONSTRAINT FK_digujantecomic_dibujante_codigodibujante FOREIGN KEY (codigoDibujante)
REFERENCES dibujante (codigodibujante) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detalleventa`
--
CREATE TABLE detalleventa (
  codigoDetalleVenta int(11) NOT NULL,
  codigoComic bigint(20) DEFAULT NULL,
  numeroVenta int(11) DEFAULT NULL,
  cantidad int(11) DEFAULT NULL,
  PRIMARY KEY (codigoDetalleVenta)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_comic_codigoComic FOREIGN KEY (codigoComic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detalleventa
ADD CONSTRAINT FK_detalleventa_venta_numeroVenta FOREIGN KEY (numeroVenta)
REFERENCES venta (numeroVenta) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `detallecompra`
--
CREATE TABLE detallecompra (
  codigodetallecompra int(11) NOT NULL,
  codigocomic bigint(20) NOT NULL,
  numerocompra int(11) NOT NULL,
  cantidad int(11) DEFAULT NULL,
  PRIMARY KEY (codigodetallecompra, codigocomic, numerocompra)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE detallecompra
ADD CONSTRAINT FK_detallecompra_comic_codigoComic FOREIGN KEY (codigocomic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE detallecompra
ADD CONSTRAINT FK_detallecompra_compra_numerocompra FOREIGN KEY (numerocompra)
REFERENCES compra (numerocompra) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `comicpersonajes`
--
CREATE TABLE comicpersonajes (
  códigoComic bigint(20) NOT NULL,
  códigoPersonaje int(11) NOT NULL,
  PRIMARY KEY (códigoComic, códigoPersonaje)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE comicpersonajes
ADD CONSTRAINT FK_comicpersonajes_comic_codigoComic FOREIGN KEY (códigoComic)
REFERENCES comic (codigoComic) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE comicpersonajes
ADD CONSTRAINT FK_comicpersonajes_personajes_codigoPersonaje FOREIGN KEY (códigoPersonaje)
REFERENCES personajes (codigoPersonaje) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `guionistacomic2`
--
CREATE TABLE guionistacomic2 (
  codigoGuionista int(11) NOT NULL,
  codigoComic bigint(20) NOT NULL,
  PRIMARY KEY (codigoGuionista, codigoComic)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `dibujantecomic`
--
CREATE TABLE dibujantecomic (
  codigoDibujante int(11) NOT NULL,
  codigoComic bigint(20) NOT NULL,
  PRIMARY KEY (codigoDibujante, codigoComic)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table distribuidora
--
-- Table tiendacomics.distribuidora does not contain any data (it is empty)

-- 
-- Dumping data for table guionista
--
-- Table tiendacomics.guionista does not contain any data (it is empty)

-- 
-- Dumping data for table dibujante
--
-- Table tiendacomics.dibujante does not contain any data (it is empty)

-- 
-- Dumping data for table venta
--
-- Table tiendacomics.venta does not contain any data (it is empty)

-- 
-- Dumping data for table compra
--
-- Table tiendacomics.compra does not contain any data (it is empty)

-- 
-- Dumping data for table personajes
--
-- Table tiendacomics.personajes does not contain any data (it is empty)

-- 
-- Dumping data for table comic
--
INSERT INTO comic VALUES
(1, '1', 1, 2001, '1', NULL, 1),
(15, 'pooo', 5, 1995, '2ooo', NULL, 54);

-- 
-- Dumping data for table tipoespecial
--
-- Table tiendacomics.tipoespecial does not contain any data (it is empty)

-- 
-- Dumping data for table guionistacomic2
--
-- Table tiendacomics.guionistacomic2 does not contain any data (it is empty)

-- 
-- Dumping data for table guionistacomic
--
-- Table tiendacomics.guionistacomic does not contain any data (it is empty)

-- 
-- Dumping data for table facturac
--
-- Table tiendacomics.facturac does not contain any data (it is empty)

-- 
-- Dumping data for table factura
--
-- Table tiendacomics.factura does not contain any data (it is empty)

-- 
-- Dumping data for table digujantecomic
--
-- Table tiendacomics.digujantecomic does not contain any data (it is empty)

-- 
-- Dumping data for table dibujantecomic
--
-- Table tiendacomics.dibujantecomic does not contain any data (it is empty)

-- 
-- Dumping data for table detalleventa
--
-- Table tiendacomics.detalleventa does not contain any data (it is empty)

-- 
-- Dumping data for table detallecompra
--
-- Table tiendacomics.detallecompra does not contain any data (it is empty)

-- 
-- Dumping data for table comicpersonajes
--
-- Table tiendacomics.comicpersonajes does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;